-- MySQL Script generated by MySQL Workbench
-- Fri Jan 30 01:21:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema swiftauction_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema swiftauction_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swiftauction_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `swiftauction_db` ;

-- -----------------------------------------------------
-- Table `swiftauction_db`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `description` VARCHAR(120) NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `status` VARCHAR(20) NULL,
  `createDate` DATETIME NULL,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Role_idx` (`idRole` ASC)  ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  ,
  CONSTRAINT `fk_User_Role`
    FOREIGN KEY (`idRole`)
    REFERENCES `swiftauction_db`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`Item` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(120) NULL,
  `status` VARCHAR(20) NULL,
  `condition` VARCHAR(10) NULL,
  `createDate` DATETIME NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `fk_Item_User1_idx` (`idUser` ASC)  ,
  CONSTRAINT `fk_Item_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `swiftauction_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`Categorie` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(120) NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`Item_Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`Item_Categorie` (
  `idCategorie` INT NOT NULL,
  `idItem` INT NOT NULL,
  INDEX `fk_Item_Categorie_Categorie1_idx` (`idCategorie` ASC)  ,
  INDEX `fk_Item_Categorie_Item1_idx` (`idItem` ASC)  ,
  CONSTRAINT `fk_Item_Categorie_Categorie1`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `swiftauction_db`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Categorie_Item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `swiftauction_db`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`Image` (
  `idImage` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `path` VARCHAR(512) NULL,
  `createDate` DATETIME NULL,
  PRIMARY KEY (`idImage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`Item_Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`Item_Image` (
  `idItem` INT NOT NULL,
  `idImage` INT NOT NULL,
  INDEX `fk_Item_Image_Item1_idx` (`idItem` ASC)  ,
  INDEX `fk_Item_Image_Image1_idx` (`idImage` ASC)  ,
  CONSTRAINT `fk_Item_Image_Item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `swiftauction_db`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Image_Image1`
    FOREIGN KEY (`idImage`)
    REFERENCES `swiftauction_db`.`Image` (`idImage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`Auction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`Auction` (
  `idAuction` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATETIME NULL,
  `endDate` DATETIME NULL,
  `initialPrice` FLOAT NULL,
  `status` VARCHAR(20) NULL,
  `idUser` INT NOT NULL,
  `idItem` INT NOT NULL,
  PRIMARY KEY (`idAuction`),
  INDEX `fk_Auction_User1_idx` (`idUser` ASC)  ,
  INDEX `fk_Auction_Item1_idx` (`idItem` ASC)  ,
  CONSTRAINT `fk_Auction_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `swiftauction_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auction_Item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `swiftauction_db`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`Bid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`Bid` (
  `idbid` INT NOT NULL AUTO_INCREMENT,
  `amount` FLOAT NULL,
  `createDate` DATETIME NULL,
  `idUser` INT NOT NULL,
  `idAuction` INT NOT NULL,
  PRIMARY KEY (`idbid`),
  INDEX `fk_Bid_User1_idx` (`idUser` ASC)  ,
  INDEX `fk_Bid_Auction1_idx` (`idAuction` ASC)  ,
  CONSTRAINT `fk_Bid_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `swiftauction_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bid_Auction1`
    FOREIGN KEY (`idAuction`)
    REFERENCES `swiftauction_db`.`Auction` (`idAuction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`Invoice` (
  `idInvoice` INT NOT NULL AUTO_INCREMENT,
  `idAuction` INT NOT NULL,
  `status` VARCHAR(20) NULL,
  `createDate` DATETIME NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`idInvoice`),
  INDEX `fk_Invoice_Auction1_idx` (`idAuction` ASC)  ,
  CONSTRAINT `fk_Invoice_Auction1`
    FOREIGN KEY (`idAuction`)
    REFERENCES `swiftauction_db`.`Auction` (`idAuction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`Card` (
  `idCard` INT NOT NULL AUTO_INCREMENT,
  `cardName` VARCHAR(100) NOT NULL,
  `cardNumber` VARCHAR(64) NOT NULL,
  `expMonth` VARCHAR(64) NOT NULL,
  `expYear` VARCHAR(64) NOT NULL,
  `securityCode` VARCHAR(64) NOT NULL,
  `lastDigits` VARCHAR(4) NULL,
  PRIMARY KEY (`idCard`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiftauction_db`.`User_Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swiftauction_db`.`User_Card` (
  `Card_idCard` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  INDEX `fk_table1_Card1_idx` (`Card_idCard` ASC)  ,
  INDEX `fk_table1_User1_idx` (`User_idUser` ASC)  ,
  CONSTRAINT `fk_table1_Card1`
    FOREIGN KEY (`Card_idCard`)
    REFERENCES `swiftauction_db`.`Card` (`idCard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `swiftauction_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
